name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Visual Studio 2019
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        cmake --build . --config Release
    - name: Releases
      uses: actions/upload-artifact@v3.1.2
      with:
        name: releases
        path: ../bin/vs17/msvc-19.35/x86_64/release/
      
